@startuml trainModel

    object train
    object trainTracks
    object mainCar

    object wagons
    object control
    object controlGoal
    object stop
    object advance
    object goBack
    object whistle
    object player
    object playerGoal
    object drive

    train *-- mainCar
    
    mainCar o-- wagons
    mainCar <.. control
    
    train *-- trainTracks

    player *-- playerGoal
    drive -right-|> playerGoal

    control o-left- player
    control *-- controlGoal
    controlGoal <|-- stop
    controlGoal <|-- advance
    controlGoal <|-- goBack
    controlGoal <|-- whistle

    

@enduml