@startuml trainModel

    object trainGame
    object train
    object trainTracks
    object lineTracks
    object addTracks
    
    object wagons
    object wagonsGoal
    object addWagon
    object control
    object controlGoal
    object stop
    object advance
    object goBack
    object whistle
    object player
    object playerGoal
    object drive

    trainGame *-- train
    trainGame *-- player
    
    train o-- wagons
    train <.. control
    
    trainGame *-- trainTracks
    addTracks -right-|> trainTracks
    trainTracks *-- lineTracks

    wagons *-- wagonsGoal
    addWagon -left-|> wagonsGoal

    player *-- playerGoal
    drive -right-|> playerGoal

    control <.left. player
    control *-- controlGoal
    controlGoal <|-- stop
    controlGoal <|-- advance
    controlGoal <|-- goBack
    controlGoal <|-- whistle

    

@enduml